sudo: required
language: python
services:
  - docker
python:
  - "3.6"
before_script:
  - make compose-build
script:
  - make ci
after_script:
  - make compose-down

notifications:
  email: false

cache:
  pip: true
