sudo: required

language: generic

services:
  - docker

before_script:
  - docker-compose build

script:
 - docker-compose run -e CODECOV_TOKEN=$CODECOV_TOKEN --rm web bash -c "cd {{cookiecutter.app_name}} && j-crypto-create-pair && cd .. && create_keys.py && flake8 {{cookiecutter.app_name}} && mypy {{cookiecutter.app_name}} && python wait_for_postgres.py && cd {{cookiecutter.app_name}} && coverage run manage.py test -v 2 && coverage html && codecov"        
after_script:
  - docker-compose down

notifications:
  email: false

cache:
  pip: true
